# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Shower Thoughts"
description: > # this means to ignore newlines until "email:"
   Stories | Novels | Opinions

email: kp@spotrot.com
#blog logo
logo: "/assets/images/splogo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/header.jpg"

name: 'Kiran Prasad'
author: 'Kiran Prasad'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://kiranprasad2001.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@kiranprasad2001'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/kiranprasad2001
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon: facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/kiranprasad2001
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: readme  # New entry for Substack
    url:  https://kiranprasad2001.substack.com 
    desc: Subscribe to my Substack
    share_url:  # You might need to find Substack's share URL if they have one
    share_title:  
    share_link: 

  - icon: medium  # New entry for Medium
    url:  https://medium.com/@kiranprasad2001
    desc: Read my stories on Medium
    share_url: https://medium.com/m/global-share?url=  # Medium's share URL
    share_title: 
    share_link: 

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
